"""agregar modelo mensaje procesado

Revision ID: 1a43525d1f9a
Revises: 975fcda49959
Create Date: 2025-12-08 04:02:08.787237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a43525d1f9a'
down_revision: Union[str, Sequence[str], None] = '975fcda49959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensaje_procesado',
    sa.Column('id_mensaje_procesado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje_id', sa.String(length=100), nullable=False),
    sa.Column('contenido', sa.String(length=1000), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mensaje_procesado'),
    sa.UniqueConstraint('mensaje_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje_procesado')
    # ### end Alembic commands ###
