"""tipo_mensaje dentro de MensajeProcesado

Revision ID: 68f581ec325a
Revises: 1a43525d1f9a
Create Date: 2025-12-08 14:14:06.119300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f581ec325a'
down_revision: Union[str, Sequence[str], None] = '1a43525d1f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensaje_procesado', sa.Column('tipo_mensaje', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensaje_procesado', 'tipo_mensaje')
    # ### end Alembic commands ###
