"""initial tables

Revision ID: 853d233e48ae
Revises: 89a7bb8b4b19
Create Date: 2025-11-05 21:07:24.379484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853d233e48ae'
down_revision: Union[str, Sequence[str], None] = '89a7bb8b4b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticia', sa.Column('contenido', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticia', 'contenido')
    # ### end Alembic commands ###
