"""initial tables

Revision ID: 89a7bb8b4b19
Revises: 
Create Date: 2025-11-05 19:57:10.376670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a7bb8b4b19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dominio',
    sa.Column('id_dominio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_dominio', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_dominio')
    )
    op.create_table('etiqueta',
    sa.Column('id_etiqueta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_etiqueta', sa.String(length=100), nullable=False),
    sa.Column('id_etiqueta_wordpress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_etiqueta')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_telefono', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('permiso', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('numero_telefono')
    )
    op.create_table('noticia',
    sa.Column('id_noticia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('url_noticia', sa.String(length=500), nullable=False),
    sa.Column('url_imagen', sa.String(length=500), nullable=True),
    sa.Column('id_dominio', sa.Integer(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dominio'], ['dominio.id_dominio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_noticia'),
    sa.UniqueConstraint('url_noticia')
    )
    op.create_table('noticia_etiqueta',
    sa.Column('id_noticia_etiqueta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticia.id_noticia'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_noticia_etiqueta')
    )
    op.create_table('publicacion_wordpress',
    sa.Column('id_wordpress', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('id_post_wordpress', sa.Integer(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticia.id_noticia'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_wordpress'),
    sa.UniqueConstraint('id_post_wordpress')
    )
    op.create_table('usuario_noticia',
    sa.Column('id_usuario_noticia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('vista', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticia.id_noticia'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_noticia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_noticia')
    op.drop_table('publicacion_wordpress')
    op.drop_table('noticia_etiqueta')
    op.drop_table('noticia')
    op.drop_table('usuario')
    op.drop_table('etiqueta')
    op.drop_table('dominio')
    # ### end Alembic commands ###
