"""nueva migracion

Revision ID: 975fcda49959
Revises: b7eb1519cd98
Create Date: 2025-12-07 23:08:04.722622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975fcda49959'
down_revision: Union[str, Sequence[str], None] = 'b7eb1519cd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noticia', 'id_dominio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('usuario_noticia', sa.Column('fecha_vista', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_noticia', 'fecha_vista')
    op.alter_column('noticia', 'id_dominio',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
